gpio:
  - gpio: 34
    state: 0
    mode: INPUT
    intr: ANYEDGE
    pullup: DISABLE
    pulldown: ENABLE

  - gpio: 35
    state: 0
    mode: INPUT
    intr: ANYEDGE
    pullup: DISABLE
    pulldown: ENABLE

  - gpio: 36
    state: 0
    mode: INPUT
    intr: ANYEDGE
    pullup: DISABLE
    pulldown: ENABLE

  - gpio: 37
    state: 0
    mode: INPUT
    intr: ANYEDGE
    pullup: DISABLE
    pulldown: ENABLE

uart:
  - uart_num: 0
    state: 0
    rx_gpio: 1
    tx_gpio: 2
    baudrate: 115200

  - uart_num: 1
    state: 0
    rx_gpio: 3
    tx_gpio: 4
    baudrate: 115200

  - uart_num: 2
    state: 0
    rx_gpio: 5
    tx_gpio: 33
    baudrate: 115200
